services:
  nginx:
    image: nginx:alpine
    ports:
      - "82:82"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html

  
  frontend:
    build: ./frontend

  backend:
    build: ./backend
    ports:
      - "3000:3000" 
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/app 
      - /app/node_modules

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: netotrack
    ports:
      - "3307:3306"
    volumes:
      - ./netotrack.sql:/docker-entrypoint-initdb.d/netotrack.sql
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: